name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 0.13.3)"
        required: true
        type: string

jobs:
  build:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux-aarch64
            runner: blacksmith-2vcpu-ubuntu-2404-arm
          - platform: macos-aarch64
            runner: macos-26
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Verify architecture
        run: |
          echo "Platform: ${{ matrix.platform }}"
          echo "Runner: ${{ matrix.runner }}"
          uname -a
          uname -m
          if [ "$(uname -m)" != "aarch64" ] && [ "$(uname -m)" != "arm64" ]; then
            echo "ERROR: Not running on ARM64/AArch64 architecture!"
            echo "Expected: aarch64 or arm64, Got: $(uname -m)"
            exit 1
          fi
          echo "✓ Architecture verified: $(uname -m)"

      - name: Install dependencies (Linux)
        if: matrix.platform == 'linux-aarch64'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool texinfo

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-aarch64'
        run: |
          brew install autoconf automake libtool texinfo

      - name: Build
        run: |
          sh ./autogen.sh
          ./configure --enable-release --disable-docs --disable-bindings
          make -j$(nproc)
          make install DESTDIR=$PWD/install-root
          mv install-root libredwg-${{ inputs.version }}-${{ matrix.platform }}
          
          cd libredwg-${{ inputs.version }}-${{ matrix.platform }}/usr/local
          
          # Fix RPATH to make binaries relocatable
          if [ "${{ matrix.platform }}" = "macos-aarch64" ]; then
            # macOS: Use install_name_tool
            for bin in bin/*; do
              if [ -f "$bin" ] && [ -x "$bin" ]; then
                install_name_tool -add_rpath @executable_path/../lib "$bin" 2>/dev/null || true
                install_name_tool -change /usr/local/lib/libredwg.0.dylib @rpath/libredwg.0.dylib "$bin" 2>/dev/null || true
              fi
            done
          else
            # Linux: Use patchelf
            sudo apt-get install -y patchelf
            for bin in bin/*; do
              if [ -f "$bin" ] && [ -x "$bin" ]; then
                patchelf --set-rpath '$ORIGIN/../lib' "$bin" 2>/dev/null || true
              fi
            done
          fi
          
          cd ../../..
          tar -czf libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz libredwg-${{ inputs.version }}-${{ matrix.platform }}

      - name: Generate install script
        run: |
          sed -e 's/VERSION_PLACEHOLDER/${{ inputs.version }}/g' \
              -e 's/PLATFORM_PLACEHOLDER/${{ matrix.platform }}/g' \
              .github/install-template.sh > install-${{ matrix.platform }}.sh
          chmod +x install-${{ matrix.platform }}.sh

      - name: Generate checksum
        run: |
          sha256sum libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz > libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libredwg-${{ inputs.version }}-${{ matrix.platform }}
          path: |
            libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz
            libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz.sha256
            install-${{ matrix.platform }}.sh
          retention-days: 90

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: LibreDWG ${{ inputs.version }}
          body: |
            Prebuilt binaries for AArch64 (ARM64) platforms.

            ## Quick Install

            **Linux AArch64:**
            ```bash
            curl -fsSL https://github.com/rite-build/libredwg/releases/download/${{ inputs.version }}/install-linux-aarch64.sh | sh
            ```

            **macOS AArch64:**
            ```bash
            curl -fsSL https://github.com/rite-build/libredwg/releases/download/${{ inputs.version }}/install-macos-aarch64.sh | sh
            ```

            Or download manually and install with custom prefix:
            ```bash
            ./install-linux-aarch64.sh --prefix /custom/path
            ./install-macos-aarch64.sh --system  # installs to /usr/local
            ```

            ## Upstream
            https://github.com/LibreDWG/libredwg/releases/tag/${{ inputs.version }}
          files: |
            libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz
            libredwg-${{ inputs.version }}-${{ matrix.platform }}.tar.gz.sha256
            install-${{ matrix.platform }}.sh
          draft: false
          prerelease: false
